from __future__ import annotations

from decimal import Decimal

from fpdf import FPDF

from core.model import Invoice

# Page geometry (A4 portrait, mm)
_LM = 20   # left margin
_RM = 20   # right margin
_W  = 170  # usable width (210 - 20 - 20)

_LABEL = {"en": {
    "invoice":    "INVOICE",
    "credit_note":"CREDIT NOTE",
    "issue_date": "Issue date",
    "due_date":   "Due date",
    "currency":   "Currency",
    "type_code":  "Type",
    "ruleset":    "Ruleset",
    "seller":     "Seller",
    "buyer":      "Buyer",
    "vat":        "VAT ID",
    "lines":      "Line items",
    "col_id":     "#",
    "col_desc":   "Description",
    "col_qty":    "Qty / Unit",
    "col_price":  "Unit price",
    "col_vat":    "VAT",
    "col_net":    "Net",
    "net_total":  "Net total",
    "allowances": "Allowances",
    "charges":    "Charges",
    "excl_vat":   "Total excl. VAT",
    "vat_amount": "VAT",
    "incl_vat":   "Total incl. VAT",
    "prepaid":    "Prepaid",
    "amount_due": "AMOUNT DUE",
    "generated":  "Generated by einvoice-reader.com",
}, "de": {
    "invoice":    "RECHNUNG",
    "credit_note":"GUTSCHRIFT",
    "issue_date": "Rechnungsdatum",
    "due_date":   "Faelligkeitsdatum",
    "currency":   "Waehrung",
    "type_code":  "Typ",
    "ruleset":    "Regelwerk",
    "seller":     "Verkaeufer",
    "buyer":      "Kaeufer",
    "vat":        "USt-IdNr.",
    "lines":      "Rechnungspositionen",
    "col_id":     "#",
    "col_desc":   "Bezeichnung",
    "col_qty":    "Menge / Einh.",
    "col_price":  "Einzelpreis",
    "col_vat":    "MwSt.",
    "col_net":    "Netto",
    "net_total":  "Nettobetrag",
    "allowances": "Nachlaesse",
    "charges":    "Abgaben",
    "excl_vat":   "Betrag ohne MwSt.",
    "vat_amount": "MwSt.-Betrag",
    "incl_vat":   "Betrag mit MwSt.",
    "prepaid":    "Bereits gezahlt",
    "amount_due": "FAELLIGER BETRAG",
    "generated":  "Erstellt von einvoice-reader.com",
}}


def _fmt(amount: Decimal) -> str:
    return f"{amount:,.2f}"


class _PDF(FPDF):
    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(160, 160, 160)
        self.cell(0, 5, f"Page {self.page_no()}", align="C")


def build(invoice: Invoice, locale: str = "en") -> bytes:
    """Return raw PDF bytes for *invoice*."""
    t = _LABEL.get(locale, _LABEL["en"])
    cur = invoice.currency

    pdf = _PDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(_LM, 15, _RM)
    pdf.add_page()

    # ── Title row ──────────────────────────────────────────────────────
    doc_type = t["credit_note"] if invoice.type_code == "381" else t["invoice"]
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, doc_type, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, invoice.number, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Meta grid (2-column) ───────────────────────────────────────────
    col = _W / 2

    def meta_row(left_label: str, left_val: str, right_label: str = "", right_val: str = "") -> None:
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(col, 5, left_label.upper(), new_x="RIGHT", new_y="TOP")
        if right_label:
            pdf.cell(col, 5, right_label.upper())
        pdf.ln(5)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(col, 5, left_val, new_x="RIGHT", new_y="TOP")
        if right_val:
            pdf.cell(col, 5, right_val)
        pdf.ln(6)

    meta_row(
        t["issue_date"], str(invoice.issue_date),
        t["currency"],   cur,
    )
    if invoice.due_date:
        meta_row(t["due_date"], str(invoice.due_date))

    pdf.ln(4)
    _hline(pdf)
    pdf.ln(5)

    # ── Parties ────────────────────────────────────────────────────────
    col = _W / 2

    def party_block(label: str, party) -> None:
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(col, 5, label.upper())

    party_block(t["seller"], invoice.seller)
    party_block(t["buyer"],  invoice.buyer)
    pdf.ln(5)

    def party_lines(party) -> list[str]:
        lines = [party.name]
        if party.vat_id:
            lines.append(f"{t['vat']}: {party.vat_id}")
        if party.address:
            a = party.address
            if a.street:
                lines.append(a.street)
            city_line = " ".join(filter(None, [a.postcode, a.city]))
            if city_line:
                lines.append(city_line)
            if a.country:
                lines.append(a.country)
        return lines

    seller_lines = party_lines(invoice.seller)
    buyer_lines  = party_lines(invoice.buyer)
    max_lines    = max(len(seller_lines), len(buyer_lines))

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(30, 30, 30)
    for i in range(max_lines):
        sl = seller_lines[i] if i < len(seller_lines) else ""
        bl = buyer_lines[i]  if i < len(buyer_lines)  else ""
        pdf.cell(col, 5, sl, new_x="RIGHT", new_y="TOP")
        pdf.cell(col, 5, bl)
        pdf.ln(5)

    pdf.ln(6)
    _hline(pdf)
    pdf.ln(5)

    # ── Line items table ───────────────────────────────────────────────
    if invoice.lines:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 6, t["lines"], new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # column widths: id, description, qty/unit, price, vat, net
        cw = [8, 72, 22, 26, 18, 24]

        # header row
        pdf.set_fill_color(245, 245, 245)
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(100, 100, 100)
        headers = [t["col_id"], t["col_desc"], t["col_qty"], t["col_price"], t["col_vat"], t["col_net"]]
        aligns  = ["L", "L", "R", "R", "R", "R"]
        for w, h, a in zip(cw, headers, aligns):
            pdf.cell(w, 6, h, border="B", fill=True, align=a)
        pdf.ln(6)

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(30, 30, 30)
        for line in invoice.lines:
            vat_str = line.vat_category
            if line.vat_rate is not None:
                vat_str += f" {line.vat_rate}%"
            price_str = f"{cur} {_fmt(line.unit_price)}" if line.unit_price is not None else "-"
            row = [
                line.id,
                line.item_name[:45],
                f"{_fmt(line.quantity)} {line.unit}",
                price_str,
                vat_str,
                f"{cur} {_fmt(line.net_amount)}",
            ]
            row_h = 6
            for w, val, a in zip(cw, row, aligns):
                pdf.cell(w, row_h, val, border="B", align=a)
            pdf.ln(row_h)

        pdf.ln(6)

    # ── Totals ─────────────────────────────────────────────────────────
    if invoice.totals:
        tot = invoice.totals
        label_w = 90
        val_w   = _W - label_w

        def total_row(label: str, amount: Decimal, bold: bool = False, color=(80, 80, 80)) -> None:
            pdf.set_font("Helvetica", "B" if bold else "", 9)
            pdf.set_text_color(*color)
            pdf.cell(_LM + label_w, 5, "", new_x="RIGHT", new_y="TOP")  # left indent
            pdf.cell(0, 5, "", new_x="LMARGIN", new_y="TOP")            # reset (unused)
            # Use set_x to right-align the two-column block
            pdf.set_x(_LM + label_w - label_w)
            pdf.set_x(_LM)
            pdf.cell(label_w, 5, label, align="R", new_x="RIGHT", new_y="TOP")
            pdf.cell(val_w,   5, f"{cur} {_fmt(amount)}", align="R")
            pdf.ln(5)

        total_row(t["net_total"],  tot.line_net_total)
        if tot.allowances:
            total_row(t["allowances"], tot.allowances)
        if tot.charges:
            total_row(t["charges"],    tot.charges)
        total_row(t["excl_vat"],   tot.tax_exclusive)
        total_row(t["vat_amount"], tot.tax_amount)

        pdf.set_x(_LM)
        pdf.set_draw_color(200, 200, 200)
        x = pdf.get_x()
        y = pdf.get_y()
        pdf.line(_LM, y, _LM + _W, y)
        pdf.ln(2)

        total_row(t["incl_vat"],   tot.tax_inclusive, bold=True)
        if tot.prepaid:
            total_row(t["prepaid"],    tot.prepaid)

        pdf.ln(1)
        pdf.set_x(_LM)
        y = pdf.get_y()
        pdf.line(_LM, y, _LM + _W, y)
        pdf.ln(3)

        total_row(t["amount_due"], tot.due, bold=True, color=(20, 80, 160))

    # ── Generated-by note ─────────────────────────────────────────────
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(180, 180, 180)
    pdf.cell(0, 5, t["generated"], align="C")

    return bytes(pdf.output())


def _hline(pdf: FPDF) -> None:
    pdf.set_draw_color(220, 220, 220)
    y = pdf.get_y()
    pdf.line(_LM, y, _LM + _W, y)
